home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from Question.models import Questionnaire


class HomeView(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        questionnaires = Questionnaire.objects.all()
        context = super(HomeView, self).get_context_data()
        context['questionnaires'] = questionnaires
        return context

students/views.py
import random
from django.shortcuts import render, redirect
from django.views import View
from Question.models import Question, Option, Category, FinalResult
from .models import RandomQuestions
from .forms import AnswerForm
from .answers_module import Answer
from django.core.paginator import Paginator
from .page_number import Page
from .final_score import Score
from .question_module import ThisQuestion
from .form_function import FormMaker


class StudentView(View):

    def get(self, request):
        page = Page(request)

        num_page = page.current_page()
        if not bool(num_page):
            num_page = '1'
        if num_page == '1':
            questions = Question.objects.all()
            list_questions = [q for q in questions]
            random.shuffle(list_questions)

            for i in list_questions:
                RandomQuestions.objects.create(category=i.category.category_name,
                                               question_text=i.question_text,
                                               session_id=request.session)

            r_questions = RandomQuestions.objects.all()

        else:
            r_questions = RandomQuestions.objects.all()

        paginator = Paginator(r_questions, 1)
        paginated_questions = paginator.get_page(num_page)
        this_question = ThisQuestion(request)
        form = AnswerForm()
        for question in paginated_questions:
            this_question.next_question(str(question.id))
            options = Option.objects.filter(question=Question.objects.get(question_text=question.question_text))
            print(Question.objects.get(question_text=question.question_text).question_text)
            print(question.id)
            form_maker = FormMaker(options)
            print(this_question.current_question())
            form.fields['field'].label = Question.objects.get(question_text=question.question_text).question_text
            form.fields['field'].choices = form_maker.options_maker()

        return render(request, 'students/students_view.html', {'form': form, 'page': num_page})

    def post(self, request):
        form = AnswerForm(data=request.POST)
        answer = Answer(request)
        page = Page(request)
        this_question = ThisQuestion(request)
        if form.is_valid():
            choice = form.cleaned_data.get('field')
            question = Question.objects.get(question_text=RandomQuestions.objects.get(id=int(this_question.current_question())).question_text)
            choice_ob = Option.objects.filter(question=question)
            selected_answer = choice_ob[int(choice) - 1]
            answer.add(question.question_text, selected_answer, selected_answer.score)
            num_page = page.current_page()
            next_page = int(num_page) + 1
            if next_page > Question.counter.count():
                page.next_page('1')
                RandomQuestions.objects.all().delete()
                return redirect('score')
            page.next_page(str(next_page))
            return redirect('student_view')


class ShowScoreView(View):

    def get(self, request):
        answer = Answer(request)
        categories = Category.objects.all()
        score_class = Score(request)
        score = score_class.final_score(request)
        categories_scores = score_class.all_category_scores(categories, request)
        result = FinalResult.objects.last()
        return render(request, 'students/score_view.html',
                      {'answer': answer, 'score': score, 'categories_scores': categories_scores, 'result': result})


class CategoryView(View):
    def get(self, request, slug):
        category = Category.objects.get(slug=slug)
        answer = Answer(request)
        score_class = Score(request)
        score = score_class.category_final_score(category, request)
        return render(request, 'students/category_detail.html',
                      {'answer': answer, 'score': score, 'category': category})

templates/footer.html
{% load static %}
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Behance</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Dribbble</a></li>
            </ul>
          </div>
          <div class="col-lg-12">
            <div class="copyright-text">
              <p>Copyright 2020 Stand Blog Co.

                 | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>
        <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/accordions.js' %}"></script>

    <script language = "text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>

templates/head.html
{% load static %}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home:home_page' %}"><h2>HealthySoul<em></em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:home_page' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'question:all_questionnaires' %}">Questionnaires</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'question:contact' %}">Contact Us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>